name: Send to Teams

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  send_message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Send message to Teams
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"text": "Hello from GitHub!"}' $WEBHOOK_URL
